Homework 2
meirabeloritskaya/Online_store pull request #2
Opened 2024-09-15 13:24 UTC by meirabeloritskaya

2024-09-15 17:15 UTC, painassasin requested changes

2024-09-15 17:15 UTC, painassasin commented on catalog/models.py
Дата создания продукта и дата изменения продукта должны быть DateTimeField и выставляться автоматически через auto_now_add и auto_now соответственно

2024-09-15 17:15 UTC, painassasin commented on catalog/admin.py
> +class AuthorAdmin(admin.ModelAdmin):
Класс относится к категории, а значит называться должен CategoryAdmin, ниже тоже

2024-09-16 05:22 UTC, meirabeloritskaya commented on catalog/admin.py
> +class AuthorAdmin(admin.ModelAdmin):
)))) исправила

2024-09-16 15:58 UTC, painassasin requested changes

2024-09-16 15:58 UTC, painassasin commented on catalog/management/commands/add_products.py
> +                    "created_at": date(2024, 9, 10),
Так как поле изменилось на datetime, то и тут нужно указать datetime

2024-09-16 15:58 UTC, painassasin commented on catalog/models.py
> +    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
Изменены поля, но миграции не увидел(

2024-09-16 15:58 UTC, painassasin commented on .flake8
> +ignore = E203, W503
Эти ошибки игнорировать не нужно

2024-09-17 19:48 UTC, merged